const mockData = {
  destinations: [
    // HIMALAYAN & NORTH INDIA
    {
      name: "Kashmir - Paradise on Earth",
      slug: "kashmir",
      category: "Himalayan",
      stateOrCountry: "Jammu & Kashmir, India",
      heroImage: "images/kashimr.jpg",
      gallery: ["images/kashimr.jpg"],
      overview: "Experience serene Shikara rides on Dal Lake, snow-covered gondola rides in Gulmarg, and pine valleys of Pahalgam.",
      history: "Ancient Himalayan valley renowned for Mughal royal gardens and cashmere craftsmanship.",
      climate: "Alpine Spring & Autumn (10°C - 22°C), Snowy Winter (-5°C to 8°C).",
      bestTimeToVisit: "April to October for greenery, December to February for skiing.",
      thingsToDo: ["Shikara Ride on Dal Lake", "Gondola Cable Car Ride in Gulmarg", "Pahalgam Valley Trekking"],
      coordinates: { lat: 34.0837, lng: 74.7973 },
      popularAttractions: [{ name: "Dal Lake", category: "Nature", image: "images/kashimr.jpg", description: "Iconic houseboats & sunset Shikaras." }],
      nearbyHotelsCount: 24,
      nearestAirport: "Srinagar International Airport (SXR)",
      averageCostPerDayINR: 6500,
      averageCostPerDayUSD: 85,
      isFeatured: true,
      rating: 4.9,
      reviewsCount: 312
    },
    {
      name: "Leh Ladakh - Land of High Passes",
      slug: "leh-ladakh",
      category: "Himalayan",
      stateOrCountry: "Ladakh, India",
      heroImage: "images/leh.jpg",
      gallery: ["images/leh.jpg"],
      overview: "Dazzling blue Pangong Tso, Nubra Valley sand dunes, and Khardung La bike expeditions.",
      history: "Strategic stopover on the ancient Silk Route.",
      climate: "Cool Summers (15°C - 25°C), Sub-zero Winters.",
      bestTimeToVisit: "May to September.",
      thingsToDo: ["Pangong Lake Camping", "Khardung La Pass Ride", "Monastery Tour"],
      coordinates: { lat: 34.1526, lng: 77.5771 },
      popularAttractions: [{ name: "Pangong Tso", category: "Lake", image: "images/leh.jpg", description: "High altitude color-changing lake." }],
      nearbyHotelsCount: 18,
      nearestAirport: "Leh Kushok Bakula Airport (IXL)",
      averageCostPerDayINR: 7500,
      averageCostPerDayUSD: 95,
      isFeatured: true,
      rating: 5.0,
      reviewsCount: 240
    },
    {
      name: "Himachal Pradesh - Shimla, Manali & Spiti",
      slug: "himachal-pradesh",
      category: "Himalayan",
      stateOrCountry: "Himachal Pradesh, India",
      heroImage: "images/himachal.jpg",
      gallery: ["images/himachal.jpg"],
      overview: "Colonial Shimla Mall Road, Solang Valley paragliding, Dharamshala monasteries, and Spiti cold desert.",
      history: "Headquarters of Daffodil Himalayan (Reg: 11-2279/2024-DTO-SML).",
      climate: "Pleasant Summers (15°C - 28°C), Snowy Winters.",
      bestTimeToVisit: "Year round destination.",
      thingsToDo: ["Solang Valley Paragliding", "Spiti Monastery Trail", "Shimla Heritage Walk"],
      coordinates: { lat: 31.1048, lng: 77.1734 },
      popularAttractions: [{ name: "Solang Valley", category: "Adventure", image: "images/himachal.jpg", description: "Paragliding & snow sports." }],
      nearbyHotelsCount: 40,
      nearestAirport: "Jubbarhatti Airport, Shimla / Bhuntar Manali",
      averageCostPerDayINR: 5500,
      averageCostPerDayUSD: 70,
      isFeatured: true,
      rating: 4.88,
      reviewsCount: 410
    },
    {
      name: "Uttarakhand - Devbhoomi & Auli Skiing",
      slug: "uttarakhand",
      category: "Spiritual",
      stateOrCountry: "Uttarakhand, India",
      heroImage: "images/utrakhand.jpg",
      gallery: ["images/utrakhand.jpg"],
      overview: "Holy river confluences in Rishikesh, Mussoorie hill sanctuary, Auli ski slopes, and Kedarnath Dham.",
      history: "Sacred land of the Vedas and Char Dham pilgrimages.",
      climate: "Cool Alpine Weather.",
      bestTimeToVisit: "May to June, September to November.",
      thingsToDo: ["Rishikesh Ganga Aarti & Rafting", "Auli Ropeway Ride", "Mussoorie Mall Road"],
      coordinates: { lat: 30.0869, lng: 78.2676 },
      popularAttractions: [{ name: "Triveni Ghat", category: "Sacred", image: "images/utrakhand.jpg", description: "Spiritual Ganga Aarti." }],
      nearbyHotelsCount: 30,
      nearestAirport: "Jolly Grant Airport, Dehradun (DED)",
      averageCostPerDayINR: 5200,
      averageCostPerDayUSD: 65,
      isFeatured: true,
      rating: 4.92,
      reviewsCount: 295
    },

    // SACRED TEMPLE DESTINATIONS
    {
      name: "Kedarnath & Badrinath Dham",
      slug: "kedarnath-badrinath",
      category: "Spiritual",
      stateOrCountry: "Uttarakhand, India",
      heroImage: "images/kedarnath&badrinath.jpg",
      gallery: ["images/kedarnath&badrinath.jpg"],
      overview: "Lord Shiva's ancient Himalayan Kedarnath shrine and Lord Vishnu's holy Badrinath temple with helicopter shuttle.",
      history: "Established by Adi Shankaracharya in the 8th century.",
      climate: "Cold Himalayan Climate (2°C - 15°C).",
      bestTimeToVisit: "May to June, September to October.",
      thingsToDo: ["VIP Pooja & Darshan", "Helicopter Shuttle Flight", "Mana First Indian Village Visit"],
      coordinates: { lat: 30.7346, lng: 79.0669 },
      popularAttractions: [{ name: "Kedarnath Temple", category: "Jyotirlinga", image: "images/kedarnath&badrinath.jpg", description: "Sacred 12th Jyotirlinga." }],
      nearbyHotelsCount: 15,
      nearestAirport: "Dehradun Helipad / Airport",
      averageCostPerDayINR: 8500,
      averageCostPerDayUSD: 105,
      isFeatured: true,
      rating: 5.0,
      reviewsCount: 520
    },
    {
      name: "Varanasi, Ayodhya & Haridwar",
      slug: "varanasi-ayodhya",
      category: "Spiritual",
      stateOrCountry: "Uttar Pradesh, India",
      heroImage: "images/ayodhya.jpg",
      gallery: ["images/ayodhya.jpg"],
      overview: "Kashi Vishwanath Corridor, Sunset Ganga Aarti in Varanasi, and the grand Shri Ram Janmabhoomi Mandir in Ayodhya.",
      history: "World's oldest continuously inhabited living spiritual city.",
      climate: "Moderate Winter (10°C - 24°C).",
      bestTimeToVisit: "October to March.",
      thingsToDo: ["Subah-e-Banaras Boat Tour", "Ayodhya Ram Mandir VIP Darshan", "Kashi Corridor Walk"],
      coordinates: { lat: 25.3176, lng: 82.9739 },
      popularAttractions: [{ name: "Ayodhya Ram Mandir", category: "Sacred", image: "images/ayodhya.jpg", description: "Grand temple of Lord Ram." }],
      nearbyHotelsCount: 35,
      nearestAirport: "Varanasi / Ayodhya Airport",
      averageCostPerDayINR: 4800,
      averageCostPerDayUSD: 60,
      isFeatured: true,
      rating: 4.95,
      reviewsCount: 380
    },
    {
      name: "Golden Temple Amritsar & Vaishno Devi",
      slug: "amritsar-vaishno-devi",
      category: "Spiritual",
      stateOrCountry: "Punjab & J&K, India",
      heroImage: "images/veshnodevi.jpg",
      gallery: ["images/veshnodevi.jpg"],
      overview: "Sacred Harmandir Sahib (Golden Temple) in Amritsar and Katra Mata Vaishno Devi shrine trek.",
      history: "Sikh spiritual capital and holy Mata Vaishno Devi cave shrine.",
      climate: "Pleasant Autumn & Spring.",
      bestTimeToVisit: "September to April.",
      thingsToDo: ["Golden Temple Langar & Pavitra Sarovar", "Wagah Border Ceremony", "Katra Helicopter Ride"],
      coordinates: { lat: 31.6200, lng: 74.8765 },
      popularAttractions: [{ name: "Mata Vaishno Devi Shrine", category: "Sacred", image: "images/veshnodevi.jpg", description: "Sacred cave shrine in Katra." }],
      nearbyHotelsCount: 28,
      nearestAirport: "Jammu / Amritsar Airport",
      averageCostPerDayINR: 4200,
      averageCostPerDayUSD: 52,
      isFeatured: true,
      rating: 4.94,
      reviewsCount: 290
    },

    // HERITAGE DESTINATIONS
    {
      name: "Rajasthan - Royal Forts & Palaces",
      slug: "rajasthan",
      category: "Heritage",
      stateOrCountry: "Rajasthan, India",
      heroImage: "images/rajasthan.jpg",
      gallery: ["images/rajasthan.jpg"],
      overview: "Jaipur Amber Fort, Udaipur Lake Palace, Jodhpur Blue City, and Jaisalmer Thar Desert luxury glamping.",
      history: "Land of Rajput Maharajas and royal fortresses.",
      climate: "Warm Sunny Weather (15°C - 28°C in Winter).",
      bestTimeToVisit: "October to March.",
      thingsToDo: ["Udaipur Lake Pichola Boat Cruise", "Thar Desert Camel Safari", "Amer Fort Elephant Ride"],
      coordinates: { lat: 26.9124, lng: 75.7873 },
      popularAttractions: [{ name: "Mehrangarh Fort", category: "Heritage", image: "images/rajasthan.jpg", description: "Majestic Jodhpur fortress." }],
      nearbyHotelsCount: 50,
      nearestAirport: "Jaipur / Udaipur Airport",
      averageCostPerDayINR: 7800,
      averageCostPerDayUSD: 98,
      isFeatured: true,
      rating: 4.91,
      reviewsCount: 340
    },
    {
      name: "Agra & Delhi - Taj Mahal & UNESCO Sites",
      slug: "agra-delhi",
      category: "Heritage",
      stateOrCountry: "Delhi & UP, India",
      heroImage: "images/tajmehal.jpg",
      gallery: ["images/tajmehal.jpg"],
      overview: "The world wonder Taj Mahal in Agra, Qutub Minar, Humayun's Tomb, and Red Fort in Delhi.",
      history: "Seat of the Mughal Empire and ancient Indian capitals.",
      climate: "Pleasant Winter Months.",
      bestTimeToVisit: "October to March.",
      thingsToDo: ["Sunrise Taj Mahal Guided Tour", "Old Delhi Chandni Chowk Rikshaw Ride", "Qutub Minar Walk"],
      coordinates: { lat: 27.1751, lng: 78.0421 },
      popularAttractions: [{ name: "Taj Mahal", category: "Wonder", image: "images/tajmehal.jpg", description: "Iconic white marble monument." }],
      nearbyHotelsCount: 45,
      nearestAirport: "Indira Gandhi International Airport, Delhi (DEL)",
      averageCostPerDayINR: 6200,
      averageCostPerDayUSD: 80,
      isFeatured: true,
      rating: 4.96,
      reviewsCount: 480
    },
    {
      name: "Hampi & South Heritage Ruins",
      slug: "hampi-karnataka",
      category: "Heritage",
      stateOrCountry: "Karnataka, India",
      heroImage: "images/southheritage.jpg",
      gallery: ["images/southheritage.jpg"],
      overview: "UNESCO World Heritage boulder ruins of Vijayanagara Empire stone chariots and Vitthala temple.",
      history: "Capital of the prosperous 14th century Vijayanagara Empire.",
      climate: "Warm Tropical Weather.",
      bestTimeToVisit: "November to February.",
      thingsToDo: ["Stone Chariot Photography", "Tungabhadra Coracle Ride", "Sunset Coracle Sunset"],
      coordinates: { lat: 15.3350, lng: 76.4600 },
      popularAttractions: [{ name: "Vitthala Temple", category: "UNESCO", image: "images/southheritage.jpg", description: "Famous stone chariot." }],
      nearbyHotelsCount: 16,
      nearestAirport: "Jindal Vijayanagar Airport, Toranagallu",
      averageCostPerDayINR: 4500,
      averageCostPerDayUSD: 58,
      isFeatured: false,
      rating: 4.88,
      reviewsCount: 175
    },

    // TROPICAL & INTERNATIONAL DESTINATIONS
    {
      name: "Kerala Backwaters & Munnar Tea Hills",
      slug: "kerala",
      category: "Beach",
      stateOrCountry: "Kerala, India",
      heroImage: "images/kerela.jpg",
      gallery: ["images/kerela.jpg"],
      overview: "Luxury houseboat cruises in Alleppey backwaters, Munnar tea plantations, and Kovalam beaches.",
      history: "God's Own Country, famed for ancient spice trade and Ayurveda.",
      climate: "Tropical Warm (24°C - 32°C).",
      bestTimeToVisit: "September to March.",
      thingsToDo: ["Overnight Alleppey Houseboat Cruise", "Munnar Tea Factory Tour", "Ayurvedic Massage"],
      coordinates: { lat: 9.4981, lng: 76.3388 },
      popularAttractions: [{ name: "Alleppey Backwaters", category: "Nature", image: "images/kerela.jpg", description: "Pristine palm-lined canals." }],
      nearbyHotelsCount: 38,
      nearestAirport: "Cochin International Airport (COK)",
      averageCostPerDayINR: 6000,
      averageCostPerDayUSD: 78,
      isFeatured: true,
      rating: 4.93,
      reviewsCount: 310
    },
    {
      name: "Goa & Andaman Island Beaches",
      slug: "goa-andaman",
      category: "Beach",
      stateOrCountry: "Goa & Andaman, India",
      heroImage: "images/goa.jpg",
      gallery: ["images/goa.jpg"],
      overview: "Portuguese architecture in Old Goa, luxury beach resorts, and Havelock Island Radhanagar Beach in Andaman.",
      history: "Former Portuguese colony and pristine coral islands.",
      climate: "Warm Coastal Sunshine.",
      bestTimeToVisit: "November to April.",
      thingsToDo: ["Havelock Scuba Diving", "Sunset Catamaran Cruise", "Old Goa Basilica Tour"],
      coordinates: { lat: 15.2993, lng: 74.1240 },
      popularAttractions: [{ name: "Goa Beaches", category: "Beach", image: "images/goa.jpg", description: "Asia's finest golden sand beaches." }],
      nearbyHotelsCount: 60,
      nearestAirport: "Dabolim / Mopa Airport Goa",
      averageCostPerDayINR: 6800,
      averageCostPerDayUSD: 85,
      isFeatured: true,
      rating: 4.89,
      reviewsCount: 450
    },
    {
      name: "Maldives Luxury Overwater Atolls",
      slug: "maldives",
      category: "International",
      stateOrCountry: "Maldives",
      heroImage: "images/maldives.jpg",
      gallery: ["images/maldives.jpg"],
      overview: "Overwater luxury bungalows, private island resorts, seaplane transfers, and undersea dining.",
      history: "Tropical maritime paradise in the Indian Ocean.",
      climate: "Tropical Warm Sunshine (26°C - 31°C).",
      bestTimeToVisit: "November to April.",
      thingsToDo: ["Private Yacht Charter", "Undersea Dining", "Manta Ray Snorkeling"],
      coordinates: { lat: 3.2028, lng: 73.2207 },
      popularAttractions: [{ name: "Male Atoll", category: "Overwater", image: "images/maldives.jpg", description: "Private luxury water villas." }],
      nearbyHotelsCount: 45,
      nearestAirport: "Velana International Airport, Male (MLE)",
      averageCostPerDayINR: 35000,
      averageCostPerDayUSD: 420,
      isFeatured: true,
      rating: 4.95,
      reviewsCount: 189
    },
    {
      name: "Dubai, Bali & International Sanctuaries",
      slug: "dubai-bali-international",
      category: "International",
      stateOrCountry: "UAE, Indonesia, Thailand",
      heroImage: "images/dubai.jpg",
      gallery: ["images/dubai.jpg"],
      overview: "Burj Khalifa & desert safari in Dubai, Ubud rice terraces in Bali, and Phuket island cruises.",
      history: "Global modern wonder metropolises and serene South East Asian sanctuaries.",
      climate: "Sunny Desert / Tropical Monsoon.",
      bestTimeToVisit: "October to April.",
      thingsToDo: ["Burj Khalifa At The Top", "Ubud Monkey Forest Walk", "Phuket Phi Phi Island Speedboat"],
      coordinates: { lat: 25.2048, lng: 55.2708 },
      popularAttractions: [{ name: "Burj Khalifa", category: "Wonder", image: "images/dubai.jpg", description: "World's tallest skyscraper." }],
      nearbyHotelsCount: 80,
      nearestAirport: "Dubai International Airport (DXB)",
      averageCostPerDayINR: 18000,
      averageCostPerDayUSD: 220,
      isFeatured: true,
      rating: 4.91,
      reviewsCount: 230
    }
  ],
  packages: [
    {
      title: "Scenic Himachal, Shimla & Manali Premium Tour",
      slug: "scenic-himachal-shimla-manali-tour",
      destination: "Himachal Pradesh",
      country: "India",
      durationDays: 6,
      durationNights: 5,
      priceINR: 17999,
      priceUSD: 220,
      discountPercentage: 10,
      rating: 4.88,
      reviewsCount: 120,
      image: "images/himachal.jpg",
      overview: "A premium 6-day voyage through the scenic Ridge of Shimla, paragliding in Solang Valley, Manali old town, and cold deserts of Spiti Valley.",
      inclusions: ["4-Star Deluxe Hotel Stays", "Private VIP Chauffeur Transfer", "Daily Breakfast & Dinner", "Guided Sightseeing in Shimla & Manali", "Solang Valley Adventure Activity Pass"],
      exclusions: ["Flight tickets to Chandigarh/Bhuntar", "Personal expenses"],
      badges: { isBestSeller: true, isFamilyFriendly: true, isAdventure: true, isLuxury: true, isTempleTour: false, isHeritage: false },
      itinerary: [
        { day: 1, title: "Shimla Arrival & Ridge Walk", description: "VIP transfer from Chandigarh/Kalka, Ridge walk, Mall Road tour.", icon: "fa-plane-arrival", activityType: "Arrival" },
        { day: 2, title: "Kufri Adventure Park & Green Valley", description: "Scenic pony rides, snow views, yak riding in Kufri hills.", icon: "fa-mountain", activityType: "Sightseeing" },
        { day: 3, title: "Scenic Drive to Manali via Kullu Valley", description: "Enroute visit Kullu shawl weaving factories, river rafting.", icon: "fa-route", activityType: "Sightseeing" },
        { day: 4, title: "Solang Valley Paragliding & Snow Sports", description: "Paragliding, zorbing, and ropeway rides at Solang valley.", icon: "fa-parachute-box", activityType: "Adventure" },
        { day: 5, title: "Hadimba Temple & Manali Old Town", description: "Visit ancient Hadimba Devi pine forest temple, Vashisht hot springs.", icon: "fa-gopuram", activityType: "Sightseeing" },
        { day: 6, title: "Departure to Chandigarh Airport", description: "Transfer back to Chandigarh for homeward departure flight.", icon: "fa-plane-departure", activityType: "Departure" }
      ]
    },
    {
      title: "Royal Kashmir & Gulmarg Luxury Sanctuary Expedition",
      slug: "royal-kashmir-luxury-expedition",
      destination: "Kashmir",
      country: "India",
      durationDays: 6,
      durationNights: 5,
      priceINR: 19999,
      priceUSD: 240,
      discountPercentage: 10,
      rating: 4.95,
      reviewsCount: 142,
      image: "images/kashimr.jpg",
      overview: "An opulent 6-day royal voyage through Srinagar's luxury houseboats, Mughal gardens, private Gondola rides in Gulmarg, and pine valleys of Paghalgam.",
      inclusions: ["5-Star Luxury Resort Stay", "Private VIP Chauffeur Transfer", "Daily Gourmet Breakfast & Dinner", "Shikara Sunset Cruise on Dal Lake", "Gulmarg Gondola Phase 1 & 2 Passes", "Personalized Butler Service"],
      exclusions: ["International Flight Tickets", "Personal Laundry & Beverages", "Travel Insurance Coverage"],
      badges: { isBestSeller: true, isFamilyFriendly: true, isAdventure: false, isLuxury: true, isTempleTour: false, isHeritage: false },
      itinerary: [
        { day: 1, title: "Arrival in Srinagar & Royal Houseboat Check-in", description: "VIP airport transfer, welcome traditional Kahwa tea, sunset Shikara ride on Dal Lake.", icon: "fa-plane-arrival", activityType: "Arrival" },
        { day: 2, title: "Mughal Gardens & Historic Old City Tour", description: "Private guided tour of Shalimar Bagh, Nishat Bagh, and saffron market.", icon: "fa-landmark", activityType: "Sightseeing" },
        { day: 3, title: "Gulmarg Gondola Ride & Alpine Ski Slopes", description: "Ascend to Phase 2 Kongdoori summit via Asia's highest cable car.", icon: "fa-mountain", activityType: "Adventure" },
        { day: 4, title: "Pahalgam Valley of Shepherds & Betaab River", description: "Scenic drive through pine forests, horse riding across Baisaran meadows.", icon: "fa-tree", activityType: "Sightseeing" },
        { day: 5, title: "Aru Valley Stream Walk & Fireside Dinner", description: "Excursion to pristine Aru Valley followed by chef's curated Kashmiri Wazwan.", icon: "fa-utensils", activityType: "Luxury" },
        { day: 6, title: "Pashmina Shopping & Airport Departure", description: "Morning craft shopping for authentic Pashmina shawls before airport transfer.", icon: "fa-plane-departure", activityType: "Departure" }
      ]
    },
    {
      title: "Sacred Char Dham & Kedarnath Yatra",
      slug: "sacred-kedarnath-badrinath-pilgrimage",
      destination: "Char Dham & Uttarakhand",
      country: "India",
      durationDays: 7,
      durationNights: 6,
      priceINR: 21999,
      priceUSD: 270,
      discountPercentage: 15,
      rating: 5.0,
      reviewsCount: 98,
      image: "images/kedarnath&badrinath.jpg",
      overview: "Divine Himalayan spiritual Yatra covering Lord Shiva's Kedarnath Dham and Lord Vishnu's Badrinath Temple with priority VIP Darshan & option of Helicopter shuttle.",
      inclusions: ["Helicopter Shuttle Services", "Luxury Eco-Lodge Stays", "VIP Temple Darshan Passes", "Pure Vegetarian Gourmet Cuisine", "Dedicated Expedition Doctor & Escort"],
      exclusions: ["Personal Pony Charges", "Extra Porter Fees"],
      badges: { isBestSeller: true, isFamilyFriendly: true, isAdventure: false, isLuxury: true, isTempleTour: true, isHeritage: true },
      itinerary: [
        { day: 1, title: "Rishikesh Holy Sangam & Ganga Aarti", description: "Dehradun airport arrival, transfer to Rishikesh riverside ashram, Ganga Aarti.", icon: "fa-place-of-worship", activityType: "Arrival" },
        { day: 2, title: "Drive to Guptkashi along Alaknanda River", description: "Scenic mountain road along holy river confluences.", icon: "fa-route", activityType: "Sightseeing" },
        { day: 3, title: "Helicopter Flight to Sacred Kedarnath Dham", description: "Morning helicopter flight to Kedarnath valley, VIP Pooja at temple shrine.", icon: "fa-gopuram", activityType: "Temple" },
        { day: 4, title: "Kedarnath Morning Abhishek & Guptkashi Return", description: "Sunrise Darshan and helicopter descent back to valley lodge.", icon: "fa-sun", activityType: "Temple" },
        { day: 5, title: "Journey to Badrinath via Joshimath", description: "Travel through high mountain passes to sacred Badrinath town.", icon: "fa-mountain", activityType: "Sightseeing" },
        { day: 6, title: "Badrinath Tapt Kund Dip & Mana Village", description: "Holy dip at natural hot springs and visit India's first Himalayan village Mana.", icon: "fa-water", activityType: "Temple" },
        { day: 7, title: "Return to Dehradun Airport Departure", description: "Transfer to Dehradun Airport with divine blessings.", icon: "fa-plane-departure", activityType: "Departure" }
      ]
    },
    {
      title: "Golden Triangle & Taj Mahal Heritage Tour",
      slug: "royal-golden-triangle-taj-mahal",
      destination: "Agra, Delhi & Jaipur",
      country: "India",
      durationDays: 6,
      durationNights: 5,
      priceINR: 12999,
      priceUSD: 160,
      discountPercentage: 10,
      rating: 4.93,
      reviewsCount: 180,
      image: "images/tajmehal.jpg",
      overview: "Experience India's majestic heritage: Delhi Qutub Minar, sunrise Taj Mahal in Agra, and royal Amber Palace in Jaipur Pink City.",
      inclusions: ["5-Star Heritage Palace Stays", "Private VIP Chauffeur Vehicle", "Mughal & Rajasthani Fine Dining", "Private Historian Monument Escort"],
      exclusions: ["International Flights", "Personal Expenses"],
      badges: { isBestSeller: true, isFamilyFriendly: true, isAdventure: false, isLuxury: true, isTempleTour: false, isHeritage: true },
      itinerary: [
        { day: 1, title: "Delhi Arrival & Qutub Minar Tour", description: "Private airport pickup and guided tour of UNESCO Qutub Minar.", icon: "fa-landmark", activityType: "Arrival" },
        { day: 2, title: "Mughal Highway to Agra & Sunset Mehtab Bagh", description: "Express drive to Agra and view Taj Mahal across Yamuna river at sunset.", icon: "fa-sun", activityType: "Sightseeing" },
        { day: 3, title: "Sunrise Taj Mahal & Agra Fort", description: "Private early morning tour of Taj Mahal followed by Agra Fort.", icon: "fa-monument", activityType: "Heritage" },
        { day: 4, title: "Fatehpur Sikri & Jaipur Pink City Arrival", description: "Visit ghost city Fatehpur Sikri enroute to Jaipur luxury hotel.", icon: "fa-archway", activityType: "Sightseeing" },
        { day: 5, title: "Amber Fort Elephant Ride & City Palace", description: "Royal fortress ascent and private tour of Maharaja City Palace.", icon: "fa-crown", activityType: "Heritage" },
        { day: 6, title: "Delhi International Airport Transfer", description: "Return drive to Delhi Airport for homeward flight.", icon: "fa-plane-departure", activityType: "Departure" }
      ]
    },
    {
      title: "Goa Beach & Sun Sensation Tour",
      slug: "goa-beach-tour",
      destination: "Goa",
      country: "India",
      durationDays: 5,
      durationNights: 4,
      priceINR: 14999,
      priceUSD: 180,
      discountPercentage: 10,
      rating: 4.9,
      reviewsCount: 150,
      image: "images/goa.jpg",
      overview: "Explore golden sand beaches of Goa, Portuguese heritage churches, and sunset boat cruises on Mandovi river.",
      inclusions: ["3-Star Deluxe Beach Resort Stay", "Airport Transfers", "Daily Breakfast", "South Goa Guided Sightseeing Tour", "Mandovi River Sunset Cruise"],
      exclusions: ["Lunch and dinner", "Flight tickets", "Water sports charges"],
      badges: { isBestSeller: true, isFamilyFriendly: true, isAdventure: false, isLuxury: false, isTempleTour: false, isHeritage: true },
      itinerary: [
        { day: 1, title: "Goa Arrival & Beach Sunset Walk", description: "Airport pickup and transfer to beach resort, leisure sunset stroll.", icon: "fa-plane-arrival", activityType: "Arrival" },
        { day: 2, title: "North Goa Forts & Beaches", description: "Visit historic Fort Aguada, and sunbathe on Calangute & Baga beaches.", icon: "fa-sun", activityType: "Sightseeing" },
        { day: 3, title: "Old Goa Heritage & Sunset Cruise", description: "Explore Basilica of Bom Jesus, Se Cathedral, followed by Mandovi river cruise.", icon: "fa-ship", activityType: "Sightseeing" },
        { day: 4, title: "Leisure Beach Day / Water Sports", description: "Day at leisure to explore local markets, shacks, and enjoy water sports.", icon: "fa-swimming-pool", activityType: "Adventure" },
        { day: 5, title: "Departure from Goa", description: "Airport drop-off for your flight back home.", icon: "fa-plane-departure", activityType: "Departure" }
      ]
    },
    {
      title: "Leh Ladakh Bike & Jeep Expedition",
      slug: "leh-ladakh-expedition",
      destination: "Leh Ladakh",
      country: "India",
      durationDays: 6,
      durationNights: 5,
      priceINR: 17999,
      priceUSD: 220,
      discountPercentage: 10,
      rating: 4.95,
      reviewsCount: 90,
      image: "images/leh.jpg",
      overview: "An adventurous ride through Khardung La Pass, camping next to blue Pangong Lake, and visiting high-altitude monasteries.",
      inclusions: ["Comfortable Guesthouse Stays", "Inner Line Permits", "Daily Breakfast & Dinner", "Oxygen Cylinder support", "Leh Airport Transfers", "Shared Bike/Jeep tour"],
      exclusions: ["Personal riding gear", "Lunch", "Flight tickets"],
      badges: { isBestSeller: true, isFamilyFriendly: false, isAdventure: true, isLuxury: false, isTempleTour: false, isHeritage: false },
      itinerary: [
        { day: 1, title: "Leh Arrival & Acclimatization", description: "Airport pickup, rest and acclimatize to high altitude.", icon: "fa-plane-arrival", activityType: "Arrival" },
        { day: 2, title: "Leh Local Sightseeing & Confluence", description: "Visit Hall of Fame, Magnetic Hill, and Sangam of Indus & Zanskar rivers.", icon: "fa-map-marked-alt", activityType: "Sightseeing" },
        { day: 3, title: "Nubra Valley via Khardung La Pass", description: "Drive through highest motorable pass to Nubra valley, enjoy double-hump camel rides.", icon: "fa-mountain", activityType: "Adventure" },
        { day: 4, title: "Nubra to Pangong Tso via Shyok River", description: "Drive along Shyok river to the iconic color-changing Pangong Lake.", icon: "fa-route", activityType: "Sightseeing" },
        { day: 5, title: "Pangong Tso back to Leh via Chang La", description: "Witness gorgeous sunrise over Pangong lake, return to Leh via Chang La pass.", icon: "fa-backward", activityType: "Sightseeing" },
        { day: 6, title: "Leh Departure", description: "Airport transfer for your departure flight.", icon: "fa-plane-departure", activityType: "Departure" }
      ]
    },
    {
      title: "Spiti Valley & Cold Desert Adventure",
      slug: "spiti-valley-tour",
      destination: "Spiti Valley",
      country: "India",
      durationDays: 7,
      durationNights: 6,
      priceINR: 17999,
      priceUSD: 220,
      discountPercentage: 10,
      rating: 4.92,
      reviewsCount: 75,
      image: "images/Spiti Valley & Cold Desert Adventure.jpg",
      overview: "Explore the high altitude cold desert Spiti Valley, visiting ancient Key Monastery, highest villages like Hikkim & Komic, and scenic Chandratal Lake.",
      inclusions: ["Homestay and Guesthouse Stays", "Private Tour Coordinator", "Daily Breakfast & Dinner", "Chandratal Lake camping", "Transport from Manali to Manali"],
      exclusions: ["Manali travel costs", "Lunch", "Personal expenses"],
      badges: { isBestSeller: false, isFamilyFriendly: false, isAdventure: true, isLuxury: false, isTempleTour: false, isHeritage: false },
      itinerary: [
        { day: 1, title: "Manali to Kaza via Kunzum Pass", description: "Scenic drive from Manali over Rohtang and Kunzum Pass to Kaza.", icon: "fa-route", activityType: "Arrival" },
        { day: 2, title: "Key Monastery & Kibber Village", description: "Explore the magnificent Key Gompa monastery and Kibber high village.", icon: "fa-gopuram", activityType: "Sightseeing" },
        { day: 3, title: "Highest Villages: Langza, Hikkim & Komic", description: "Mail a postcard from Hikkim highest post office, see Langza Buddha statue.", icon: "fa-mail-bulk", activityType: "Sightseeing" },
        { day: 4, title: "Pin Valley & Mudh Village", description: "Excursion to Pin Valley National Park and picturesque Mudh village.", icon: "fa-tree", activityType: "Sightseeing" },
        { day: 5, title: "Kaza to Chandratal Lake", description: "Scenic trek/drive to the sacred crescent-shaped Moon Lake (Chandratal) and camp.", icon: "fa-campground", activityType: "Adventure" },
        { day: 6, title: "Chandratal to Manali", description: "Return drive to Manali via Atal Tunnel / Rohtang Pass.", icon: "fa-backward", activityType: "Sightseeing" },
        { day: 7, title: "Manali Departure", description: "Tour concludes. Depart from Manali with high mountain memories.", icon: "fa-plane-departure", activityType: "Departure" }
      ]
    },
    {
      title: "Himachal Sacred Devi Darshan Yatra",
      slug: "devi-darshan-yatra",
      destination: "Himachal Pradesh",
      country: "India",
      durationDays: 5,
      durationNights: 4,
      priceINR: 14999,
      priceUSD: 185,
      discountPercentage: 10,
      rating: 4.96,
      reviewsCount: 110,
      image: "images/himachal devi darshan.jpg",
      overview: "Holy pilgrimage covering the famous Devi temples of Himachal Pradesh including Chintpurni, Jwala Ji, Kangra Devi, Chamunda Devi, and Baglamukhi.",
      inclusions: ["3-Star Hotel Accommodations", "Private Ac Car transfer", "VIP Darshan Assistance", "Daily Breakfast & Dinner", "Dedicated Yatra Coordinator"],
      exclusions: ["Special Pooja Samagri", "Personal expenses", "Prasad charges"],
      badges: { isBestSeller: true, isFamilyFriendly: true, isAdventure: false, isLuxury: false, isTempleTour: true, isHeritage: false },
      itinerary: [
        { day: 1, title: "Una Arrival & Chintpurni Temple", description: "Una railway station arrival, transfer to Chintpurni, VIP temple darshan.", icon: "fa-train", activityType: "Arrival" },
        { day: 2, title: "Chintpurni to Jwala Ji & Baglamukhi", description: "Drive to holy Jwala Ji (flame temple) and perform rituals at Baglamukhi temple.", icon: "fa-fire", activityType: "Sightseeing" },
        { day: 3, title: "Kangra Devi & Chamunda Devi Darshan", description: "Visit Vajreshwari Temple (Kangra) and Chamunda Devi temple on the banks of Baner river.", icon: "fa-gopuram", activityType: "Sightseeing" },
        { day: 4, title: "Dharamshala Local Tour & Naina Devi", description: "Visit Dharamshala McLeod Ganj, proceed to Naina Devi hill shrine.", icon: "fa-mountain", activityType: "Sightseeing" },
        { day: 5, title: "Una/Chandigarh Departure", description: "Return transfer to Una/Chandigarh for onward journey.", icon: "fa-plane-departure", activityType: "Departure" }
      ]
    }
  ],
  hotels: [
    {
      name: "The Taj Lake Palace Luxury Resort",
      location: "Udaipur, Rajasthan",
      destinationSlug: "rajasthan",
      starRating: 5,
      overview: "Floating grand marble palace on Lake Pichola featuring royal butler service and sunset lake views.",
      image: "images/rajasthan.jpg",
      amenities: ["Private Motorboat Transfer", "Royal Spa", "Infinity Pool", "Heritage Dining"],
      rating: 4.95,
      reviewsCount: 88
    },
    {
      name: "Wildflower Hall, An Oberoi Resort",
      location: "Shimla, Himachal Pradesh",
      destinationSlug: "himachal-pradesh",
      starRating: 5,
      overview: "Luxury cedar forest sanctuary elevated at 8,300 feet with heated outdoor infinity pool facing snow peak Himalayas.",
      image: "images/himachal.jpg",
      amenities: ["Heated Outdoor Jacuzzi", "Pine Forest Trekking", "Fine Dining Bar", "Helipad"],
      rating: 4.98,
      reviewsCount: 112
    },
    {
      name: "Khyber Himalayan Resort & Spa",
      location: "Gulmarg, Jammu & Kashmir",
      destinationSlug: "kashmir",
      starRating: 5,
      overview: "Pine forest luxury resort located steps away from Gulmarg Gondola cable car with indoor heated pool.",
      image: "images/kashimr.jpg",
      amenities: ["Gondola Proximity", "L'Occitane Spa", "Heated Swimming Pool", "Kashmiri Dining"],
      rating: 4.96,
      reviewsCount: 140
    }
  ],
  flights: [
    {
      flightNumber: "AI-825",
      airline: "Air India Luxury First",
      origin: "New Delhi (DEL)",
      destination: "Srinagar (SXR)",
      departureTime: "08:30 AM",
      arrivalTime: "10:00 AM",
      duration: "1h 30m",
      stops: "Non-stop",
      priceINR: 7800,
      priceUSD: 95,
      cabinClass: "Business"
    },
    {
      flightNumber: "EK-511",
      airline: "Emirates First Class",
      origin: "Mumbai (BOM)",
      destination: "Dubai (DXB)",
      departureTime: "04:15 PM",
      arrivalTime: "06:00 PM",
      duration: "3h 15m",
      stops: "Non-stop",
      priceINR: 34500,
      priceUSD: 410,
      cabinClass: "First Class"
    },
    {
      flightNumber: "DH-HELI-01",
      airline: "Daffodil VIP Himalayan Helicopter",
      origin: "Dehradun Helipad (DED)",
      destination: "Kedarnath Dham Helipad",
      departureTime: "06:30 AM",
      arrivalTime: "07:10 AM",
      duration: "40m",
      stops: "Non-stop",
      priceINR: 12500,
      priceUSD: 160,
      cabinClass: "First Class"
    }
  ],
  bookings: [
    {
      bookingId: "DH-2026-8819",
      customerName: "Dr. Alexander Wright",
      customerEmail: "alexander.wright@luxurytravel.com",
      customerPhone: "+1 (415) 892-0192",
      packageName: "Royal Kashmir & Gulmarg Luxury Sanctuary Expedition",
      travelDate: new Date('2026-09-15'),
      travellers: { adults: 2, children: 0 },
      hotelCategory: "Luxury 5-Star Aman-Tier",
      mealPlan: "MAP (Breakfast & Dinner)",
      pickupLocation: "Srinagar International Airport",
      currency: "USD",
      basePrice: 1240,
      discountAmount: 124,
      gstAmount: 55,
      totalPrice: 1171,
      paymentStatus: "Paid",
      bookingStatus: "Confirmed",
      paymentMethod: "Stripe",
      paymentTransactionId: "TXN-STRIPE-982103",
      invoiceUrl: "/api/bookings/DH-2026-8819/invoice"
    }
  ]
};

module.exports = mockData;
